
server {
    listen 80;
    server_name ~^(.+)$;
    include mime.types;
    gzip on;
    gzip_disable "MSIE [1-6]\\.(?!.*SV1)";
    gzip_proxied any;
    gzip_comp_level 5;
    gzip_types text/plain text/css application/javascript application/x-javascript text/xml application/xml application/rss+xml text/javascript image/x-icon image/bmp image/svg+xml;
    gzip_vary on;
    client_max_body_size 50M;


        root   /var/www/html;
        index  index.html index.csr.html index.htm;

    error_page 404 403 /40x.html;
    location /40x.html {
          root /usr/share/nginx/html;
          internal;
    }

    error_page 500 502 503 504 /50x.html;
    location /50x.html {
          root /usr/share/nginx/html;
          internal;
    }

    location / {
    add_header X-Frame-Options "SAMEORIGIN";
      if ($http_range ~ "(?:\d*\s*-\s*\d*\s*,\s*){5,}") {return 416;}
      if ($http_request_range ~ "(?:\d*\s*-\s*\d*\s*,\s*){5,}") {return 416;}
      if ($request_method = 'OPTIONS') {
      add_header 'Access-Control-Allow-Origin' '*';
      add_header X-Frame-Options SAMEORIGIN;
      add_header Content-Security-Policy "default-src 'self';" always;
      add_header X-XSS-Protection "1; mode=block";
      add_header 'Access-Control-Allow-Credentials' 'true';
      add_header 'Access-Control-Allow-Methods' 'GET';
      add_header 'Access-Control-Allow-Headers' 'WCTrustedToken,WCToken,UserId,personalizationID,Session-Id,Authorization,DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
      add_header 'Access-Control-Max-Age' 1800;
      add_header 'Content-Type' 'text/plain charset=UTF-8';
      add_header 'Content-Length' 0;
      return 204;
    }
        try_files $uri$args $uri$args/ /index.csr.html;
    }
}

